Header header

geometry_msgs/Vector3 curpos
geometry_msgs/Vector3 despos

float64 cur_alpha
float64 des_alpha

float64 cur_beta
float64 des_beta

geometry_msgs/Vector3 curvel
geometry_msgs/Vector3 desvel

geometry_msgs/Vector3 curacc
geometry_msgs/Vector3 desacc

geometry_msgs/Vector3 poserr_u
geometry_msgs/Vector3 poserr_a
geometry_msgs/Vector3 velerr_u
geometry_msgs/Vector3 velerr_a
 				

geometry_msgs/Quaternion curor
geometry_msgs/Quaternion desor

float64 thrust
float64 gamma
float64 rho
float64 Kp0
float64 Kp1
