Header header

geometry_msgs/Vector3 curpos
geometry_msgs/Vector3 despos

geometry_msgs/Vector3 curvel
geometry_msgs/Vector3 desvel

geometry_msgs/Vector3 curacc
geometry_msgs/Vector3 desacc

geometry_msgs/Vector3 poserr
geometry_msgs/Vector3 velerr

geometry_msgs/Quaternion curor
geometry_msgs/Quaternion desor

float64 thrust

float64 M1_pos_err
float64 M2_pos_err
float64 M1_vel_err
float64 M2_vel_err

