(cl:in-package msg_check-msg)
(cl:export '(HEADER-VAL
          HEADER
          CURPOS-VAL
          CURPOS
          DESPOS-VAL
          DESPOS
          CURVEL-VAL
          CURVEL
          DESVEL-VAL
          DESVEL
          CURACC-VAL
          CURACC
          DESACC-VAL
          DESACC
          POSERR-VAL
          POSERR
          VELERR-VAL
          VELERR
          CUROR-VAL
          CUROR
          DESOR-VAL
          DESOR
          THRUST-VAL
          THRUST
          M1_POS_ERR-VAL
          M1_POS_ERR
          M2_POS_ERR-VAL
          M2_POS_ERR
          M1_VEL_ERR-VAL
          M1_VEL_ERR
          M2_VEL_ERR-VAL
          M2_VEL_ERR
))