(cl:in-package msg_check-msg)
(cl:export '(HEADER-VAL
          HEADER
          SP-VAL
          SP
          SQ-VAL
          SQ
          ACCELERATION-VAL
          ACCELERATION
          ANGULAR_ACCELERATION-VAL
          ANGULAR_ACCELERATION
          POSITION_ERROR-VAL
          POSITION_ERROR
          VELOCITY_ERROR-VAL
          VELOCITY_ERROR
          POSITION_ERROR_INTEGRAL-VAL
          POSITION_ERROR_INTEGRAL
          ANGLE_ERROR-VAL
          ANGLE_ERROR
          ANGLE_RATE_ERROR-VAL
          ANGLE_RATE_ERROR
          KP0_1-VAL
          KP0_1
          KP1_1-VAL
          KP1_1
          KP0_2-VAL
          KP0_2
          KP1_2-VAL
          KP1_2
          KP0_3-VAL
          KP0_3
          KP1_3-VAL
          KP1_3
          KQ0_1-VAL
          KQ0_1
          KQ1_1-VAL
          KQ1_1
          KQ2_1-VAL
          KQ2_1
          KQ0_2-VAL
          KQ0_2
          KQ1_2-VAL
          KQ1_2
          KQ2_2-VAL
          KQ2_2
          KQ0_3-VAL
          KQ0_3
          KQ1_3-VAL
          KQ1_3
          KQ2_3-VAL
          KQ2_3
          RHO_P0_1-VAL
          RHO_P0_1
          RHO_P1_1-VAL
          RHO_P1_1
          RHO_P0_2-VAL
          RHO_P0_2
          RHO_P1_2-VAL
          RHO_P1_2
          RHO_P0_3-VAL
          RHO_P0_3
          RHO_P1_3-VAL
          RHO_P1_3
          RHO_Q0_1-VAL
          RHO_Q0_1
          RHO_Q1_1-VAL
          RHO_Q1_1
          RHO_Q2_1-VAL
          RHO_Q2_1
          RHO_Q0_2-VAL
          RHO_Q0_2
          RHO_Q1_2-VAL
          RHO_Q1_2
          RHO_Q2_2-VAL
          RHO_Q2_2
          RHO_Q0_3-VAL
          RHO_Q0_3
          RHO_Q1_3-VAL
          RHO_Q1_3
          RHO_Q2_3-VAL
          RHO_Q2_3
          ZETA_P-VAL
          ZETA_P
          ZETA_Q-VAL
          ZETA_Q
          DELTAU_P-VAL
          DELTAU_P
          DELTAU_Q-VAL
          DELTAU_Q
          MOMENTS-VAL
          MOMENTS
          THRUST-VAL
          THRUST
          HATM_1-VAL
          HATM_1
          HATM_2-VAL
          HATM_2
          HATM_3-VAL
          HATM_3
))